### ISSUE TITLE
Trying to get this to work

### ISSUE THREAD

**Issue by andrewthedina** [julihoh/pdf_annotation_fix#1] opened 2021-07-07 10:57 UTC
Hi there. Thanks for building this tool. I'm trying to use it but was unsuccessful. Would you mind providing more detailed instructions? I installed Rust per the link you provided, but now I'm getting "no permission" and "command not found" errors when copy pasting '~ cargo run -- my_messed_up.pdf fixed.pdf'. Any advice?

**Comment by julihoh** [comment] 2021-07-07 13:54
From your description it is difficult to tell what exactly has gone wrong. It would be most helpful if you could provide the exact terminal commands you used and which output they generated, including any errors. Here are some general things I assume about the setup:

* run the command inside the cloned repository folder
* to avoid permission issues, copy the pdf file you want to fix inside the cloned repository folder
* after installing rust for the first time, make sure to completely quit and re-open your terminal
* make sure you have typed the name of your pdf file correctly

Again, it would be great if you could provide a more detailed error description. Even a screenshot of when the unexpected behaviour occurs would be helpful top troubleshoot :)

Cheers

btw: can I ask you how you found this tool?

**Comment by andrewthedina** [comment] 2021-07-07 17:13
Honestly I not very savvy with Terminal. Here was my process:
1. Open terminal, paste (curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh) and hit enter to install rust
2. Quit Terminal and re-open
3. cd Desktop to get to where my file is
4. ~ cargo run -- ~ cargo run -- taketwo.pdf takethree.pdf
5. See access denied 
![Screen Shot 2021-07-07 at 1 12 40 PM](https://user-images.githubusercontent.com/48628736/124801632-0c6a2900-df25-11eb-98b6-e08a4e71bfd6.png)

**Comment by andrewthedina** [comment] 2021-07-07 17:15
I found your repo through a comment here: https://stackoverflow.com/questions/63148342/restoring-annotations-from-a-pdf-corrupted-by-macs-preview-application-from-raw

**Comment by julihoh** [comment] 2021-07-07 17:57
> Honestly I not very savvy with Terminal. Here was my process:
> 
> 1. Open terminal, paste (curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh) and hit enter to install rust
> 2. Quit Terminal and re-open
> 3. cd Desktop to get to where my file is
> 4. ~ cargo run -- ~ cargo run -- taketwo.pdf takethree.pdf
> 5. See access denied
>    ![Screen Shot 2021-07-07 at 1 12 40 PM](https://user-images.githubusercontent.com/48628736/124801632-0c6a2900-df25-11eb-98b6-e08a4e71bfd6.png)

I See, not a problem. A couple of things:

1. You need to actually clone this repository first. Do this by running `git clone https://github.com/julihoh/pdf_annotation_fix.git` in a directory of your choice. The git command usually clones the repository into a new directory, so make sure you change into that directory.
2. Next, your Terminal does not seem to have access to your Desktop directory. You should first ensure Terminal has access to your Desktop in this case by going to System Preferences > Security and Privacy  and adding the necessary permissions to the Terminal app.
3. In code snippets where people replicate a terminal session there are typically two conventions: `~` is used to signify a line that was entered into the prompt and `#` signifies a line that was not actually in the output and was added after the fact for explanatory reasons. Therefore, when pasting the command from the README of this repository, you just paste everything after the `~ ` (like this: `cargo run -- my_messed_up.pdf fixed.pdf`).
4. Just to make sure you don't do anything unintended: the program in this repository will *overwrite* the output file if it exists already. In your screenshot above, it would have overwritten `takethree.pdf`. (Also: actions like this on the Terminal are typically irreversible in contrast to, for example, deleting a file in Finder, which moves the file to the Trash, where it can be recovered from.)

Good luck! Hope it works now :) if not, don't hesitate to write again. I'd be curious to see whether the program here manages to recover something for you!

> I found your repo through a comment here: https://stackoverflow.com/questions/63148342/restoring-annotations-from-a-pdf-corrupted-by-macs-preview-application-from-raw

Good to know, thanks!

**Comment by andrewthedina** [comment] 2021-07-07 23:54
Thanks so much for the detailed help. We’re making progress! I’m not getting this error:

I did some looking around online but am struggling to find a fix.
Any ideas?

**Comment by julihoh** [comment] 2021-07-08 14:59
Great to hear there is progress. The error you are referring to seems to be missing from your comment though. Can you please retry?

**Comment by andrewthedina** [comment] 2021-07-08 22:06
![Screen Shot 2021-07-07 at 7 49 25 PM](https://user-images.githubusercontent.com/48628736/124996598-3439b980-e017-11eb-920a-18395cd788a7.png)

**Comment by andrewthedina** [comment] 2021-07-08 22:06
Sorry, I tried to send it by responding to the notification email. Do you see it now?

**Comment by julihoh** [comment] 2021-07-09 07:27
Yes, I can see it now. You seem to be trying to run the command not within the directory in which you have cloned this repository.  If you have trouble cloning the repository, you can also just download the [files through GitHub as a zip](https://github.com/julihoh/pdf_annotation_fix/archive/refs/heads/main.zip). You can extract this zip file to your desktop and remember to `cd` into the directory before executing the command (and don't forget to move the pdf file to the folder as well!)

**Comment by andrewthedina** [comment] 2021-07-09 10:58
Ah--I didn't have the PDF files in the same folder as the repo! I finally had a successful run. But it says "recovered 0 annotations", and none of my annotations have been recovered. I really appreciate you guiding me through this. I don't mean to take any more of your time, but I'm happy to update the repo and run it again if you end up pushing an update. Thanks again.

**Comment by julihoh** [comment] 2021-07-09 12:13
Good to hear you were able to run it in the end. It's unfortunate it didn't turn out to help though... your pdf may just be corrupted in a way that this tool can't fix. It's really only helpful in very specific circumstances...

I'll close this now, feel free to re-open in case you have more questions.

**Closed by julihoh** 2021-07-09 12:13 UTC

**Comment by GitShanks14** [comment] 2024-01-03 00:13
> Yes, I can see it now. You seem to be trying to run the command not within the directory in which you have cloned this repository. If you have trouble cloning the repository, you can also just download the [files through GitHub as a zip](https://github.com/julihoh/pdf_annotation_fix/archive/refs/heads/main.zip). You can extract this zip file to your desktop and remember to `cd` into the directory before executing the command (and don't forget to move the pdf file to the folder as well!)

I wrote a script to do the following:
* Move the file to be fixed into the cloned GitHub repo
* Fix the file using your command
* Move the fixed file back to the original directory the command was run from

Dropping it here for anyone who would like to use it!
```
#!/bin/sh

FNAME="$1"

DIR=$(pwd)
echo "Copying $FNAME.pdf..."
echo $DIR
cp "$DIR/$1.pdf" PATH_TO_REPO/pdf_annotation_fix/target.pdf
cd PATH_TO_REPO/pdf_annotation_fix/

echo "Fixing $FNAME.pdf"
cargo run -- target.pdf fixed.pdf

cd $DIR
mv PATH_TO_REPO/pdf_annotation_fix/fixed.pdf "$DIR/$1_fixed.pdf"
```
Notes:
* PATH_TO_REPO to be set according to your installation
* Save as 'fixpdf.sh' in a location convenient to you
* Add ```alias fixpdf='PATH_TO_SCRIPT/fixpdf.sh'``` to your zshrc for ease of use.
* Naturally, both the filename and the alias are flexible! 

Overview: ```fixpdf filename```
- Creates filename_fixed.pdf in the directory that the command was run from
